[package]
name = "qwy3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.13.1", features = [ "derive" ] }
cgmath = "0.18.0"
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.17"
wgpu = "0.16.0"
winit = "0.28.5"
